### PR TITLE
PcmHammer .netcore

### PR DESCRIPTION
**Pull request by DevX-Cipher**
Hey i rewrote PcmHammer in .net and .net core its working progress

### CODE REVIEW

**Comment by antuspcm** [comment]
This is based on pcmhammer code that is around 2 years old, and 264 commits out of date. You'll need to rebase to current if we are to accept it. 

I am not a microsoft guy (thats more NSFW) but I thought this app was .netcore. Can you explain what this changes, and why it is useful? Thanks!

**Comment by antuspcm** [comment]
This code is based on pcmhammer that is 264 commits out of date, a lot has changed since then.

If we are to accept this you'll need to rebase it from the current develop branch.

Can you please explain what this changes and why it is useful?

**Comment by DevX-Cipher** [comment]
> This is based on pcmhammer code that is around 2 years old, and 264 commits out of date. You'll need to rebase to current if we are to accept it.
> 
> I am not a microsoft guy (thats more NSFW) but I thought this app was .netcore. Can you explain what this changes, and why it is useful? Thanks!

it was done .net frame work i thought to make in .net and .netcore to improve it that is all

**Comment by Tazzi3** [comment]
> > This is based on pcmhammer code that is around 2 years old, and 264 commits out of date. You'll need to rebase to current if we are to accept it.
> > I am not a microsoft guy (thats more NSFW) but I thought this app was .netcore. Can you explain what this changes, and why it is useful? Thanks!
> 
> it was done .net frame work i thought to make in .net and .netcore to improve it that is all

Make a branch of the latest commit and convert across. I don't believe there is any compiling issues from .netframework to .netcore so no alterations other then telling project to use correct .net option.

**Comment by DevX-Cipher** [comment]
> > > This is based on pcmhammer code that is around 2 years old, and 264 commits out of date. You'll need to rebase to current if we are to accept it.
> > > I am not a microsoft guy (thats more NSFW) but I thought this app was .netcore. Can you explain what this changes, and why it is useful? Thanks!
> > 
> > 
> > it was done .net frame work i thought to make in .net and .netcore to improve it that is all
> 
> Make a branch of the latest commit and convert across. I don't believe there is any compiling issues from .netframework to .netcore so no alterations other then telling project to use correct .net option.

i did i made another brank saying pcmhammer .net core also you can not just compile with .net core like that

**Comment by Tazzi3** [comment]
> > > > This is based on pcmhammer code that is around 2 years old, and 264 commits out of date. You'll need to rebase to current if we are to accept it.
> > > > I am not a microsoft guy (thats more NSFW) but I thought this app was .netcore. Can you explain what this changes, and why it is useful? Thanks!
> > > 
> > > 
> > > it was done .net frame work i thought to make in .net and .netcore to improve it that is all
> > 
> > 
> > Make a branch of the latest commit and convert across. I don't believe there is any compiling issues from .netframework to .netcore so no alterations other then telling project to use correct .net option.
> 
> i did i made another brank saying pcmhammer .net core also you can not just compile with .net core like that

Clearly not if the code base is 2 years old and not up to date as antus has indicated??

**Pull request closed without merging**
