### PR TITLE
Converted to use J2534DotNet library, modified solution to fix compile

### PR DESCRIPTION
**Pull request by joukoy**

### CODE REVIEW

**Comment by antuspcm** [comment]
Tested and working on my P01 with my MDI.

There is the old J2534.dll in pcmlibrary, which is no longer needed and can be removed, and a *50 on line 87 of J2534.cs which can also be removed, as the UnsafePassThruMsg type has a 4128 byte data buffer which should be enough without the multiplication, unless there is a reason it is needed to support some particular device.

**Comment by antuspcm** [comment]
Thanks for the latest update. Looks good now, any comments or other testers?

**Comment by joukoy** [comment]
No comments for now. I hope it works without problems.

**Review by antuspcm — APPROVED** [review]
Working for me.

**Pull request merged**
